// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var context, drawingCanvas, game, height, width;

    drawingCanvas = document.getElementById("drawing");
    window.ok = false;
    if (drawingCanvas.getContext) {
      $('p').remove();
      context = drawingCanvas.getContext('2d');
      width = window.innerWidth;
      height = window.innerHeight;
      context.canvas.width = width;
      context.canvas.height = height;
      window.ok = true;
      window.gridsize = 19;
      game = new window.Game(width, height, context);
      $(window).on("resize", function(event) {
        return game.redrawContext();
      });
      return $(window).on("mousewheel", function(event, delta, deltaX, deltaY) {
        if (deltaY > 0) {
          if (window.gridsize < 40) {
            window.gridsize += deltaY;
          }
        } else {
          if (window.gridsize > 5) {
            window.gridsize += deltaY;
          }
        }
        return game.redrawContext();
      });
    }
  });

}).call(this);
