// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var context, drawingCanvas, game, height, width;

    drawingCanvas = document.getElementById("drawing");
    window.ok = false;
    if (drawingCanvas.getContext) {
      $('p').remove();
      context = drawingCanvas.getContext('2d');
      width = window.innerWidth;
      height = window.innerHeight;
      context.canvas.width = width;
      context.canvas.height = height;
      window.ok = true;
      window.gridsize = 20;
      return game = new window.Game(width, height, context);
    }
  });

}).call(this);
